#!/bin/bash

user=staff

case "$1" in 
	configure)
		#apply init.d defaults
		update-rc.d staff defaults
		#apply files permissions for new user
		chown -R $user:$user /opt/$user
		#reload rsyslog
		[ -x /etc/init.d/rsyslog ] && /etc/init.d/rsyslog restart
		
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
	;;
	*)
		echo "postinst called with unknown argument \$1'" >&2
		exit 1
	;;
esac

. /usr/share/debconf/confmodule

exit 0
